### ISSUE TITLE
Unexpected number of certificates

### ISSUE THREAD

**Issue by jwpage** [pwillia6/m2m-php#1]
Running the `index.php` with the test keystore provided by the USI department returns this response:

> Expired: False
> Unexpected number of certificates: 0. Event Code: [E2169]. Event Severity: [Normal]. Event Description: [The credential supplied by the initiating party is not recognized.]. User Advice: [Advise business user the certificate cannot be used for the service.  A recognized certificate will be required.]. Agency Reference: [urn:uuid:3338442f-e652-44bd-921e-6ec633b6055e]. Transaction Id: [18bd396a-5ca0-463e-96a5-4618da96202c].  

Am I missing something in creating the token request?

**Comment by jwpage** [comment]
Couldn't manage to get this working, but had success with the original repo (<https://github.com/hut6/m2m-php>)

**Comment by pwillia6** [comment]
The test certificate might be different from the one I used.    I think the other code just selects the last one where as my code allows you to specify which certificate to use:

 $usi = new VanguardClient('TEST', 'keystore-test.xml', 'Password1!', 'ABRD:27809366375_USIMachine');
 
 The 'ABRD:27809366375_USIMachine' specifies which credentials out of the XML file.
